apiVersion: v1
kind: Service
metadata: 
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mongodb
    tier: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec: 
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: database
  serviceName: mongodb-headless
  replicas: 2
  template: 
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec: 
      containers:
      - name: mongodb
        image: teja142/mongodb:optv1
      volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
# This is nothing but PVC, you can directly create here
  volumeClaimTemplates;:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 2Gi